"""initial schema

Revision ID: 70f1bb6b1257
Revises: 
Create Date: 2026-04-22 10:47:01.393812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '70f1bb6b1257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_workday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'country', 'state', name='uq_holiday_date_country_state')
    )
    op.create_index(op.f('ix_holiday_holiday_date'), 'holiday', ['holiday_date'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sage_employee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_weekly_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_sage_employee_name'), 'person', ['sage_employee_name'], unique=True)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_program_number'), 'program', ['program_number'], unique=True)
    op.create_table('person_absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('absence_type', sa.Enum('vacation', 'training', 'sick', name='absencetype'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'confirmed', 'ongoing', name='absencestatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_absence_person_id'), 'person_absence', ['person_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('project_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_budget_hours', sa.Float(), nullable=False),
    sa.Column('holiday_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('holiday_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_program_id'), 'project', ['program_id'], unique=False)
    op.create_index(op.f('ix_project_project_number'), 'project', ['project_number'], unique=True)
    op.create_table('vacation_contingent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'year', name='uq_vacation_contingent_person_year')
    )
    op.create_index(op.f('ix_vacation_contingent_person_id'), 'vacation_contingent', ['person_id'], unique=False)
    op.create_table('billing_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_euros', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_position_project_id'), 'billing_position', ['project_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_booking_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_project_id'), 'import_batch', ['project_id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('initial_hours', sa.Float(), nullable=False),
    sa.Column('current_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='milestonestatus'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'year', 'month', name='uq_milestone_project_year_month')
    )
    op.create_index(op.f('ix_milestone_project_id'), 'milestone', ['project_id'], unique=False)
    op.create_table('project_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('weekly_capacity_hours', sa.Float(), nullable=False),
    sa.Column('billing_rate_per_hour', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_membership_person_id'), 'project_membership', ['person_id'], unique=False)
    op.create_index(op.f('ix_project_membership_project_id'), 'project_membership', ['project_id'], unique=False)
    op.create_table('sage_project_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sage_project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sage_project_mapping_project_id'), 'sage_project_mapping', ['project_id'], unique=False)
    op.create_index(op.f('ix_sage_project_mapping_sage_project_name'), 'sage_project_mapping', ['sage_project_name'], unique=True)
    op.create_table('milestone_person_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('initial_hours', sa.Float(), nullable=False),
    sa.Column('current_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'person_id', name='uq_mpb_milestone_person')
    )
    op.create_index(op.f('ix_milestone_person_budget_milestone_id'), 'milestone_person_budget', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_milestone_person_budget_person_id'), 'milestone_person_budget', ['person_id'], unique=False)
    op.create_table('monthly_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('billing_position_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('total_amount_euros', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'invoiced', 'paid', name='invoicestatus'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['billing_position_id'], ['billing_position.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_invoice_project_id'), 'monthly_invoice', ['project_id'], unique=False)
    op.create_table('time_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('sage_project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sage_project_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('net_hours', sa.Float(), nullable=False),
    sa.Column('duration_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('break_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_date', 'person_id', 'project_id', 'sage_project_level', 'net_hours', name='uq_time_booking_dedup')
    )
    op.create_index(op.f('ix_time_booking_booking_date'), 'time_booking', ['booking_date'], unique=False)
    op.create_index(op.f('ix_time_booking_person_id'), 'time_booking', ['person_id'], unique=False)
    op.create_index(op.f('ix_time_booking_project_id'), 'time_booking', ['project_id'], unique=False)
    op.create_table('invoice_person_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('billing_rate_per_hour', sa.Float(), nullable=False),
    sa.Column('amount_euros', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['monthly_invoice.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_person_entry_invoice_id'), 'invoice_person_entry', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_person_entry_person_id'), 'invoice_person_entry', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_person_entry_person_id'), table_name='invoice_person_entry')
    op.drop_index(op.f('ix_invoice_person_entry_invoice_id'), table_name='invoice_person_entry')
    op.drop_table('invoice_person_entry')
    op.drop_index(op.f('ix_time_booking_project_id'), table_name='time_booking')
    op.drop_index(op.f('ix_time_booking_person_id'), table_name='time_booking')
    op.drop_index(op.f('ix_time_booking_booking_date'), table_name='time_booking')
    op.drop_table('time_booking')
    op.drop_index(op.f('ix_monthly_invoice_project_id'), table_name='monthly_invoice')
    op.drop_table('monthly_invoice')
    op.drop_index(op.f('ix_milestone_person_budget_person_id'), table_name='milestone_person_budget')
    op.drop_index(op.f('ix_milestone_person_budget_milestone_id'), table_name='milestone_person_budget')
    op.drop_table('milestone_person_budget')
    op.drop_index(op.f('ix_sage_project_mapping_sage_project_name'), table_name='sage_project_mapping')
    op.drop_index(op.f('ix_sage_project_mapping_project_id'), table_name='sage_project_mapping')
    op.drop_table('sage_project_mapping')
    op.drop_index(op.f('ix_project_membership_project_id'), table_name='project_membership')
    op.drop_index(op.f('ix_project_membership_person_id'), table_name='project_membership')
    op.drop_table('project_membership')
    op.drop_index(op.f('ix_milestone_project_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_import_batch_project_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_billing_position_project_id'), table_name='billing_position')
    op.drop_table('billing_position')
    op.drop_index(op.f('ix_vacation_contingent_person_id'), table_name='vacation_contingent')
    op.drop_table('vacation_contingent')
    op.drop_index(op.f('ix_project_project_number'), table_name='project')
    op.drop_index(op.f('ix_project_program_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_person_absence_person_id'), table_name='person_absence')
    op.drop_table('person_absence')
    op.drop_index(op.f('ix_program_program_number'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_person_sage_employee_name'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_holiday_holiday_date'), table_name='holiday')
    op.drop_table('holiday')
    # ### end Alembic commands ###
